sudo: required
services:
  - docker

install:
  - pip install PyYAML
  - pip install virtualenv
  - |
    test -e Gemfile || cat <<EOF > Gemfile
    source 'https://rubygems.org'
    gem 'rake'
    gem 'test-kitchen'
    gem 'kitchen-docker'
    gem 'kitchen-inspec'
    gem 'inspec'
    gem 'kitchen-salt', :git => 'https://github.com/salt-formulas/kitchen-salt.git'
  - bundle install

env:
  - PLATFORM=trevorj/salty-whales:trusty SUITE=replication_both MYSQL_VER=5.5
  - PLATFORM=trevorj/salty-whales:xenial SUITE=replication_both MYSQL_VER=5.7
  - PLATFORM=trevorj/salty-whales:trusty SUITE=replication_master MYSQL_VER=5.5
  - PLATFORM=trevorj/salty-whales:xenial SUITE=replication_master MYSQL_VER=5.7
  - PLATFORM=trevorj/salty-whales:trusty SUITE=replication_slave MYSQL_VER=5.5
  - PLATFORM=trevorj/salty-whales:xenial SUITE=replication_slave MYSQL_VER=5.7
  - PLATFORM=trevorj/salty-whales:trusty SUITE=server_client_database MYSQL_VER=5.5
  - PLATFORM=trevorj/salty-whales:xenial SUITE=server_client_database MYSQL_VER=5.7
  - PLATFORM=trevorj/salty-whales:trusty SUITE=server_client_user MYSQL_VER=5.5
  - PLATFORM=trevorj/salty-whales:xenial SUITE=server_client_user MYSQL_VER=5.7

before_script:
  - set -o pipefail
  - make test | tail

script:
  - test ! -e .kitchen.yml || bundle exec kitchen converge ${SUITE} || true
  - test ! -e .kitchen.yml || bundle exec kitchen verify ${SUITE} -t tests/integration

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6123573504759330786b
    on_success: change  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    on_cancel: never    # options: [always|never|change] default: always
    on_error: never    # options: [always|never|change] default: always
  email: false